version: '3.8'

services:
  # etcd cluster nodes
  etcd1:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd1
    environment:
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_ADVERTISE_PEER_URLS=http://etcd1:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd1_data:/etcd-data
    networks:
      - pam-network

  etcd2:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd2
    environment:
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_ADVERTISE_PEER_URLS=http://etcd2:2380
    volumes:
      - etcd2_data:/etcd-data
    networks:
      - pam-network

  etcd3:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd3
    environment:
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_ADVERTISE_PEER_URLS=http://etcd3:2380
    volumes:
      - etcd3_data:/etcd-data
    networks:
      - pam-network

  # Vault server
  vault:
    image: hashicorp/vault:1.15.0
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - vault_data:/vault/data
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - pam-network
    command: server -config=/vault/config/vault.hcl

volumes:
  etcd1_data:
  etcd2_data:
  etcd3_data:
  vault_data:

networks:
  pam-network:
    driver: bridge 